In [28]:
import pandas as pd
import ast
import numpy as np
import torch

df = pd.read_csv("CHIBike.geo")

In [29]:
coords = df['coordinates'][1]
parsed_coords = np.array(ast.literal_eval(coords)[0])
parsed_coords.mean(axis=0)

array([-87.7554,  41.6688])

In [30]:
df['coordinates'][2]

'[[[-87.747, 41.658], [-87.733, 41.658], [-87.733, 41.685], [-87.747, 41.685], [-87.747, 41.658]]]'

In [31]:
df['centers'] = df['coordinates'].copy()
def getCenter(strCoords):
    parsed_coords = np.array(ast.literal_eval(strCoords)[0])
    return parsed_coords.mean(axis=0)
df['centers'] = df['centers'].apply(func = getCenter).copy()

In [32]:
#vec_field = [[0]*270]*270
vec_field = [[0]*270 for _ in range(270)]
for index, row in df.iterrows():
    for index1, row1 in df.iterrows():
        delta_x = row1['centers'][0] - row['centers'][0]
        delta_y = row1['centers'][1] - row['centers'][1]
        vec_field[index][index1]= np.array([delta_x,delta_y])
        
vec_field

[[array([0., 0.]),
  array([0.0134, 0.    ]),
  array([0.0274, 0.    ]),
  array([0.041, 0.   ]),
  array([0.0544, 0.    ]),
  array([0.0684, 0.    ]),
  array([0.082, 0.   ]),
  array([0.0954, 0.    ]),
  array([0.1094, 0.    ]),
  array([0.123, 0.   ]),
  array([0.1364, 0.    ]),
  array([0.1504, 0.    ]),
  array([0.164, 0.   ]),
  array([0.1774, 0.    ]),
  array([0.1914, 0.    ]),
  array([0.205, 0.   ]),
  array([0.2184, 0.    ]),
  array([0.2324, 0.    ]),
  array([0.   , 0.027]),
  array([0.0134, 0.027 ]),
  array([0.0274, 0.027 ]),
  array([0.041, 0.027]),
  array([0.0544, 0.027 ]),
  array([0.0684, 0.027 ]),
  array([0.082, 0.027]),
  array([0.0954, 0.027 ]),
  array([0.1094, 0.027 ]),
  array([0.123, 0.027]),
  array([0.1364, 0.027 ]),
  array([0.1504, 0.027 ]),
  array([0.164, 0.027]),
  array([0.1774, 0.027 ]),
  array([0.1914, 0.027 ]),
  array([0.205, 0.027]),
  array([0.2184, 0.027 ]),
  array([0.2324, 0.027 ]),
  array([0.   , 0.054]),
  array([0.0134, 0.054 ]),
  arra

In [33]:
vec_field[4][230]

array([0.137 , 0.3254])

In [34]:
len(vec_field[0])

270

In [35]:
v_np = np.array(vec_field)

In [36]:
v_np.shape

(270, 270, 2)

In [37]:
np.save('VF_CHIBike.npy', v_np)

In [38]:
vec_field[2][2]

array([0., 0.])